#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PTVGlass.Resource", IsApplication=true)]

namespace PTVGlass
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::PTVGlass.Resource.String.library_name;
			global::GlassProgressBar.Resource.Dimension.slider_bar_height = global::PTVGlass.Resource.Dimension.slider_bar_height;
			global::GlassProgressBar.Resource.Drawable.bar_candy0001 = global::PTVGlass.Resource.Drawable.bar_candy0001;
			global::GlassProgressBar.Resource.Drawable.bar_candy0002 = global::PTVGlass.Resource.Drawable.bar_candy0002;
			global::GlassProgressBar.Resource.Drawable.bar_candy0003 = global::PTVGlass.Resource.Drawable.bar_candy0003;
			global::GlassProgressBar.Resource.Drawable.bar_candy0004 = global::PTVGlass.Resource.Drawable.bar_candy0004;
			global::GlassProgressBar.Resource.Drawable.bar_candy0005 = global::PTVGlass.Resource.Drawable.bar_candy0005;
			global::GlassProgressBar.Resource.Drawable.bar_candy0006 = global::PTVGlass.Resource.Drawable.bar_candy0006;
			global::GlassProgressBar.Resource.Drawable.bar_candy0007 = global::PTVGlass.Resource.Drawable.bar_candy0007;
			global::GlassProgressBar.Resource.Drawable.bar_candy0008 = global::PTVGlass.Resource.Drawable.bar_candy0008;
			global::GlassProgressBar.Resource.Drawable.bar_candy0009 = global::PTVGlass.Resource.Drawable.bar_candy0009;
			global::GlassProgressBar.Resource.Drawable.bar_candy0010 = global::PTVGlass.Resource.Drawable.bar_candy0010;
			global::GlassProgressBar.Resource.Drawable.bar_candy0011 = global::PTVGlass.Resource.Drawable.bar_candy0011;
			global::GlassProgressBar.Resource.Drawable.bar_candy0012 = global::PTVGlass.Resource.Drawable.bar_candy0012;
			global::GlassProgressBar.Resource.Drawable.bar_candy0013 = global::PTVGlass.Resource.Drawable.bar_candy0013;
			global::GlassProgressBar.Resource.Drawable.bar_candy0014 = global::PTVGlass.Resource.Drawable.bar_candy0014;
			global::GlassProgressBar.Resource.Drawable.bar_candy0015 = global::PTVGlass.Resource.Drawable.bar_candy0015;
			global::GlassProgressBar.Resource.Drawable.bar_candy0016 = global::PTVGlass.Resource.Drawable.bar_candy0016;
			global::GlassProgressBar.Resource.Drawable.bar_candy0017 = global::PTVGlass.Resource.Drawable.bar_candy0017;
			global::GlassProgressBar.Resource.Drawable.bar_candy0018 = global::PTVGlass.Resource.Drawable.bar_candy0018;
			global::GlassProgressBar.Resource.Drawable.bar_candy0019 = global::PTVGlass.Resource.Drawable.bar_candy0019;
			global::GlassProgressBar.Resource.Drawable.bar_candy0020 = global::PTVGlass.Resource.Drawable.bar_candy0020;
			global::GlassProgressBar.Resource.Drawable.bar_candy0021 = global::PTVGlass.Resource.Drawable.bar_candy0021;
			global::GlassProgressBar.Resource.Drawable.bar_candy0022 = global::PTVGlass.Resource.Drawable.bar_candy0022;
			global::GlassProgressBar.Resource.Drawable.bar_candy0023 = global::PTVGlass.Resource.Drawable.bar_candy0023;
			global::GlassProgressBar.Resource.Drawable.bar_candy0024 = global::PTVGlass.Resource.Drawable.bar_candy0024;
			global::GlassProgressBar.Resource.Drawable.bar_candy0025 = global::PTVGlass.Resource.Drawable.bar_candy0025;
			global::GlassProgressBar.Resource.Drawable.bar_candy0026 = global::PTVGlass.Resource.Drawable.bar_candy0026;
			global::GlassProgressBar.Resource.Drawable.bar_candy0027 = global::PTVGlass.Resource.Drawable.bar_candy0027;
			global::GlassProgressBar.Resource.Drawable.bar_candy0028 = global::PTVGlass.Resource.Drawable.bar_candy0028;
			global::GlassProgressBar.Resource.Drawable.bar_candy0029 = global::PTVGlass.Resource.Drawable.bar_candy0029;
			global::GlassProgressBar.Resource.Drawable.bar_candy0030 = global::PTVGlass.Resource.Drawable.bar_candy0030;
			global::GlassProgressBar.Resource.Drawable.slider_indeterminate = global::PTVGlass.Resource.Drawable.slider_indeterminate;
			global::GlassProgressBar.Resource.Id.indeterminate_slider = global::PTVGlass.Resource.Id.indeterminate_slider;
			global::GlassProgressBar.Resource.Id.slider_control = global::PTVGlass.Resource.Id.slider_control;
			global::GlassProgressBar.Resource.Layout.slider = global::PTVGlass.Resource.Layout.slider;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int slider_bar_height = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_candy0001 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bar_candy0002 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bar_candy0003 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bar_candy0004 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bar_candy0005 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bar_candy0006 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bar_candy0007 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bar_candy0008 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bar_candy0009 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bar_candy0010 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bar_candy0011 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bar_candy0012 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bar_candy0013 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bar_candy0014 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bar_candy0015 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bar_candy0016 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bar_candy0017 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bar_candy0018 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bar_candy0019 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bar_candy0020 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bar_candy0021 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bar_candy0022 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bar_candy0023 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bar_candy0024 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bar_candy0025 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bar_candy0026 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bar_candy0027 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bar_candy0028 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bar_candy0029 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bar_candy0030 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int BusIcon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_warning_50 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int slider_indeterminate = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int TrainIcon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int TramIcon = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int TextLine = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int TextLineNum = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int TextStop = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int TextTime = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int error_icon = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int error_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int indeterm_slider = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int indeterminate_slider = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int listview = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int loading_text = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int slider_control = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BusTramDepartureWithStationRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DepartureScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ErrorScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoadingScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int slider = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TrainDepartureRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TrainDepartureWithStationRow = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int busses_near_me = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int getting_departures = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int getting_location = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int getting_stopsnearyou = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int no_bus_stops_nearby = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int no_internet_connection = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int no_stops_nearby = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int no_train_stops_nearby = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int no_tram_stops_nearby = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int no_upcoming_departures = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int trains_departing = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int trains_near_me = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int trams_near_me = 2131165192;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Voice_BussesNearMeTrigger = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Voice_TrainsDepartingTrigger = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Voice_TrainsNearMeTrigger = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Voice_TramsNearMeTrigger = 2130968579;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
