#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SampleStopwatch.Resource", IsApplication=true)]

namespace SampleStopwatch
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int black = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_colon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_interpunc = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_lap = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_stop = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0002
			public const int centi_second = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int minute = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int second = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int seconds_view = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int stop = 2131361796;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int card_chronometer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int card_countdown = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int stopwatch = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int countdown_bip = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int start = 2131034113;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int start_stopwatch = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int stop = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int ChronometerComponent = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ChronometerIcon = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MenuTheme = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int voice_trigger_start = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
