#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GlassProgressBar.Resource", IsApplication=false)]

namespace GlassProgressBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int slider_bar_height = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int bar_candy0001 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int bar_candy0002 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int bar_candy0003 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int bar_candy0004 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int bar_candy0005 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int bar_candy0006 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int bar_candy0007 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int bar_candy0008 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int bar_candy0009 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int bar_candy0010 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int bar_candy0011 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int bar_candy0012 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int bar_candy0013 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int bar_candy0014 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int bar_candy0015 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int bar_candy0016 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int bar_candy0017 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int bar_candy0018 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int bar_candy0019 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int bar_candy0020 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int bar_candy0021 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int bar_candy0022 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int bar_candy0023 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int bar_candy0024 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int bar_candy0025 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int bar_candy0026 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int bar_candy0027 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int bar_candy0028 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int bar_candy0029 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int bar_candy0030 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int slider_indeterminate = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public static int indeterminate_slider = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int slider_control = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int slider = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
