#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GlassProgressTest.Resource", IsApplication=true)]

namespace GlassProgressTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GlassProgressBar.Resource.Dimension.slider_bar_height = global::GlassProgressTest.Resource.Dimension.slider_bar_height;
			global::GlassProgressBar.Resource.Drawable.bar_candy0001 = global::GlassProgressTest.Resource.Drawable.bar_candy0001;
			global::GlassProgressBar.Resource.Drawable.bar_candy0002 = global::GlassProgressTest.Resource.Drawable.bar_candy0002;
			global::GlassProgressBar.Resource.Drawable.bar_candy0003 = global::GlassProgressTest.Resource.Drawable.bar_candy0003;
			global::GlassProgressBar.Resource.Drawable.bar_candy0004 = global::GlassProgressTest.Resource.Drawable.bar_candy0004;
			global::GlassProgressBar.Resource.Drawable.bar_candy0005 = global::GlassProgressTest.Resource.Drawable.bar_candy0005;
			global::GlassProgressBar.Resource.Drawable.bar_candy0006 = global::GlassProgressTest.Resource.Drawable.bar_candy0006;
			global::GlassProgressBar.Resource.Drawable.bar_candy0007 = global::GlassProgressTest.Resource.Drawable.bar_candy0007;
			global::GlassProgressBar.Resource.Drawable.bar_candy0008 = global::GlassProgressTest.Resource.Drawable.bar_candy0008;
			global::GlassProgressBar.Resource.Drawable.bar_candy0009 = global::GlassProgressTest.Resource.Drawable.bar_candy0009;
			global::GlassProgressBar.Resource.Drawable.bar_candy0010 = global::GlassProgressTest.Resource.Drawable.bar_candy0010;
			global::GlassProgressBar.Resource.Drawable.bar_candy0011 = global::GlassProgressTest.Resource.Drawable.bar_candy0011;
			global::GlassProgressBar.Resource.Drawable.bar_candy0012 = global::GlassProgressTest.Resource.Drawable.bar_candy0012;
			global::GlassProgressBar.Resource.Drawable.bar_candy0013 = global::GlassProgressTest.Resource.Drawable.bar_candy0013;
			global::GlassProgressBar.Resource.Drawable.bar_candy0014 = global::GlassProgressTest.Resource.Drawable.bar_candy0014;
			global::GlassProgressBar.Resource.Drawable.bar_candy0015 = global::GlassProgressTest.Resource.Drawable.bar_candy0015;
			global::GlassProgressBar.Resource.Drawable.bar_candy0016 = global::GlassProgressTest.Resource.Drawable.bar_candy0016;
			global::GlassProgressBar.Resource.Drawable.bar_candy0017 = global::GlassProgressTest.Resource.Drawable.bar_candy0017;
			global::GlassProgressBar.Resource.Drawable.bar_candy0018 = global::GlassProgressTest.Resource.Drawable.bar_candy0018;
			global::GlassProgressBar.Resource.Drawable.bar_candy0019 = global::GlassProgressTest.Resource.Drawable.bar_candy0019;
			global::GlassProgressBar.Resource.Drawable.bar_candy0020 = global::GlassProgressTest.Resource.Drawable.bar_candy0020;
			global::GlassProgressBar.Resource.Drawable.bar_candy0021 = global::GlassProgressTest.Resource.Drawable.bar_candy0021;
			global::GlassProgressBar.Resource.Drawable.bar_candy0022 = global::GlassProgressTest.Resource.Drawable.bar_candy0022;
			global::GlassProgressBar.Resource.Drawable.bar_candy0023 = global::GlassProgressTest.Resource.Drawable.bar_candy0023;
			global::GlassProgressBar.Resource.Drawable.bar_candy0024 = global::GlassProgressTest.Resource.Drawable.bar_candy0024;
			global::GlassProgressBar.Resource.Drawable.bar_candy0025 = global::GlassProgressTest.Resource.Drawable.bar_candy0025;
			global::GlassProgressBar.Resource.Drawable.bar_candy0026 = global::GlassProgressTest.Resource.Drawable.bar_candy0026;
			global::GlassProgressBar.Resource.Drawable.bar_candy0027 = global::GlassProgressTest.Resource.Drawable.bar_candy0027;
			global::GlassProgressBar.Resource.Drawable.bar_candy0028 = global::GlassProgressTest.Resource.Drawable.bar_candy0028;
			global::GlassProgressBar.Resource.Drawable.bar_candy0029 = global::GlassProgressTest.Resource.Drawable.bar_candy0029;
			global::GlassProgressBar.Resource.Drawable.bar_candy0030 = global::GlassProgressTest.Resource.Drawable.bar_candy0030;
			global::GlassProgressBar.Resource.Drawable.slider_indeterminate = global::GlassProgressTest.Resource.Drawable.slider_indeterminate;
			global::GlassProgressBar.Resource.Id.indeterminate_slider = global::GlassProgressTest.Resource.Id.indeterminate_slider;
			global::GlassProgressBar.Resource.Id.slider_control = global::GlassProgressTest.Resource.Id.slider_control;
			global::GlassProgressBar.Resource.Layout.slider = global::GlassProgressTest.Resource.Layout.slider;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int activity_horizontal_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int activity_vertical_margin = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int slider_bar_height = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar_candy0001 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bar_candy0002 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bar_candy0003 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bar_candy0004 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bar_candy0005 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bar_candy0006 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bar_candy0007 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bar_candy0008 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bar_candy0009 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bar_candy0010 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bar_candy0011 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bar_candy0012 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bar_candy0013 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bar_candy0014 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bar_candy0015 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bar_candy0016 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bar_candy0017 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bar_candy0018 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bar_candy0019 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bar_candy0020 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bar_candy0021 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bar_candy0022 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bar_candy0023 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bar_candy0024 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bar_candy0025 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bar_candy0026 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bar_candy0027 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bar_candy0028 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bar_candy0029 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bar_candy0030 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int slider_indeterminate = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int indeterm_slider = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int indeterminate_slider = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int progress_slider = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int slider_control = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int slider = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int action_settings = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int demo_progress_bar = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int hello_world = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int demo_progress_bar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int VoiceTriggerStart = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
